# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: minhjang <minhjang@student.42seoul.kr      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/09/26 16:03:59 by minhjang          #+#    #+#              #
#    Updated: 2021/09/26 16:06:31 by minhjang         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ./main.c
OBJ = $(SRC:.c=.o)
CC = gcc
CFLAGS = -Werror -Wall -Wextra
TARGET = rush-02


.c.o :
	$(CC) $(CFLAGS) -c $< -o $@

$(TARGET) : 
