# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: minhjang <minhjang@student.42seoul.kr      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/22 17:07:33 by minhjang          #+#    #+#              #
#    Updated: 2021/12/22 17:07:34 by minhjang         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CSRC = ft*.c
CC = gcc
CFLAGS = -Werror -Wall -Wextra
OBJECT = $(CSRC:.c=.o)

TARGET = libft.a

.PHONY all clean fclean re
